name: PR-Compiling-Check

on:
  pull_request:
    branches:
      - master

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job with params and Return Result
        uses: TechMindsDev/trigger-jenkins-and-return-result@v1
        with:
          jenkins-server: ${{ secrets.JENKINS_URL }}
          jenkins-username: "gautham"
          job-params: "branch=develop"
          jenkins-pat: ${{ secrets.JENKINS_TOKEN }}
          jenkins-job: "Android-Technician-PR-Validator"
          poll-time: 10
          timeout-value: 900
          verbose: true
