name: Jenkins-Action

on: [push]

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:             
      - name: Trigger Jenkins Job and Return Result
        uses: mickeygoussetorg/trigger-jenkins-job@v1
        with:
          jenkins-server: "http://182.76.115.170:8080"
          jenkins-username: "gautham71298"
          jenkins-pat: ${{ secrets.JENKINS_TOKEN }}
          jenkins-job: "Android-Technician-PR-Validator"
          poll-time: 10
          timeout-value: 900
          verbose: true
